import "std" as std

task<int> main {
    try {
        std::println(2 + "t")
    } catch e {
        std::println(e::name)
    }

    try -> 2 + "t"
    catch exception -> std::println("Error occurred!")
}